### ISSUE TITLE
Please tell me how do i run this code? I need it for school project 😭

### ISSUE THREAD

**Issue by rashidsayyed** [kuan51/MyFitness#1]
Please provide a clear readme or a guide for requirements and steps to run.

**Comment by kuan51** [comment]
You can clone the library and then open the solution (.sln) file using Visual Studio. Then click Start. This will build and run the app. After running the program, click stop in Visual Studio to close  it. Starting the app is important, so that it builds the .exe file. If you want to run it outside of Visual Studio, you can just copy and paste that exe to your desktop or somewhere else. The exe will be under: `MyFitness_root_folder\RLMyFitnessApp\bin\Debug\RLMyFitnessApp.exe`.

I also made this for a school project, and I havent touched the code since then. I have some larger projects I am working on, so I wont be dedicating much time to this repo. Its more a portfolio item than anything else.
